---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox-chart
  namespace: netbox
spec:  
  project: default
  source:
    repoURL: 'https://github.com/barramys/netbox'
    path: netbox-chart
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    sysncOptions:
    - CreateNamespace=true

