apiVersion: v2
name: netbox-helm
version: 5.0.0
appVersion: v3.4.4
description: A Helm chart for Kubernetes
type: application
dependencies:
- name: postgresql
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled